<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['config_file']	= "cfg/cf_homepage.php";
require_once($config['config_file']);
require_once("cfg/quangcao_mau.php");
$config['total_hot_news']	= 10;
$config['total_max_view_count_news_home']	= 10;
$config['total_max_view_count_news']	= 5;
$config['total_random_news']	= 11;
$config['total_cat_news']	= 12;
// other cat news
$relate_cat['Tin12h']	= 'The-gioi';
$relate_cat['The-gioi']	= 'Van-hoa';
$relate_cat['Van-hoa']	= 'The-gioi';
$relate_cat['The-gioi']	= 'The-gioi-sao';
$relate_cat['The-gioi-sao']	= 'Camera-can-canh';
$relate_cat['Camera-can-canh']	= 'Chuyen-hau-truong';
$relate_cat['Chuyen-hau-truong']	= 'Doi-thoai';
$relate_cat['Doi-thoai']	= 'Tinh-yeu-gioi-tinh';
$relate_cat['Tinh-yeu-gioi-tinh']	= 'Chuyen-tham-kinh';
$relate_cat['Chuyen-tham-kinh']	= 'Hon-nhan-gia-dinh';
$relate_cat['Hon-nhan-gia-dinh']	= 'Chuyen-cong-so';
$relate_cat['Chuyen-cong-so']	= 'Lam-dep';
$relate_cat['Lam-dep']	= 'Thoi-trang-shopping';
$relate_cat['Thoi-trang-shopping']	= 'Song-khoe';
$relate_cat['Song-khoe']	= 'Dan-ong';
$relate_cat['Dan-ong']	= 'Vi-tinh';
$relate_cat['Vi-tinh']	= 'Dien-thoai';
$relate_cat['Dien-thoai']	= 'Hi-tech';
$relate_cat['Hi-tech']	= 'Xe-hoi-xe-may';
$relate_cat['Xe-hoi-xe-may']	= 'Phong-cach-teen';
$relate_cat['Phong-cach-teen']	= 'Tuoi-moi-lon';
$relate_cat['Tuoi-moi-lon']	= 'Chuyen-chung-minh';
$relate_cat['Chuyen-chung-minh']	= 'Giao-duc-khuyen-hoc';
$relate_cat['Giao-duc-khuyen-hoc']	= 'Tam-su';
$relate_cat['Tam-su']	= 'Trat-tu-xa-hoi';
$relate_cat['Trat-tu-xa-hoi']	= 'Ho-so-trinh-sat';
$relate_cat['Ho-so-trinh-sat']	= 'Nuoc-mat-toa-an';
$relate_cat['Nuoc-mat-toa-an']	= 'An-ninh-the-gioi';
$relate_cat['An-ninh-the-gioi']	= 'Thi-truong-tiep-thi';
$relate_cat['Thi-truong-tiep-thi']	= 'Nhip-cau-dau-tu';
$relate_cat['Nhip-cau-dau-tu']	= 'Bat-dong-san';
$relate_cat['Bat-dong-san']	= 'Thanh-dat';
$relate_cat['Thanh-dat']	= 'The-thao';
$relate_cat['The-thao']	= 'Cuoc-song-quanh-ta';
$relate_cat['Cuoc-song-quanh-ta']	= 'Video-clip';
$relate_cat['Video-clip']	= 'Goc-song-kien-truc';
$relate_cat['Goc-song-kien-truc']	= 'Nhung-dieu-ky-thu';
$relate_cat['Nhung-dieu-ky-thu']	= 'Am-thuc';
$relate_cat['Am-thuc']	= 'Cuoi-hip-mat';
$relate_cat['Cuoi-hip-mat']	= 'Tin12h';
$relate_cat['Phap-luat']	= 'Thi-truong-tiep-thi';
$relate_cat['Kinh-te']	= 'The-thao';
$relate_cat['Nhip-song-tre']	= 'Lam-dep';
$relate_cat['Show-biz']	= 'Tinh-yeu-gioi-tinh';
$relate_cat['Phong-cach-song']	= 'Vi-tinh';
$relate_cat['4-teen']	= 'Tam-su';
$relate_cat['Sanh-cong-nghe']	= 'Goc-song-kien-truc';
$relate_cat['Giai-tri']	= 'Tin12h';

$config['relate_cat']	= $relate_cat;